### ISSUE TITLE
Implement document upload

### ISSUE THREAD

**Issue by fizruk** [fizruk/telegram-bot-simple#1]
For that we need to implement `multipart/form-data` support.
There is no general support for that in servant, so I think we should wait for https://github.com/fizruk/http-api-data/issues/24.

Until then we can just copy over some code from somewhere.

**Comment by swamp-agr** [comment]
- I think this is no longer the case since `multipart/form-data` was moved into package `servant-multipart` that was further split onto `servant-multipart`, `servant-multipart-api`, `servant-multipart-client`. 
- And these packages were incorporated as dependencies for `sendDocument` via #31.
