### ISSUE TITLE
Inconsistency in parseMode fields

### ISSUE THREAD

**Issue by fetsh** [fizruk/telegram-bot-simple#115]
Some objects are using `PareseMode` type (`SendMessageRequest`, `SendDocumentRequest`, `SendPhotoRequest`, etc) for theirs parseMode field, and some others just `Text` (`SendAudioRequest`, `SendVideoRequest`, etc).

This PR #114 should fix it.

**Comment by swamp-agr** [comment]
Thank you for reporting and fixing the docs! Please find release on Hackage: https://hackage.haskell.org/package/telegram-bot-simple-0.5.1

**Comment by fetsh** [comment]
@swamp-agr I believe it wasn't the docs that was fixed, some breaking changes were introduced here.

**Comment by swamp-agr** [comment]
Thanks! Changelog fixed.
