### ISSUE TITLE
DecodeFailure on copyMessage

### ISSUE THREAD

**Issue by fetsh** [fizruk/telegram-bot-simple#117]
`copyMessage` expects `MessageId` as a result, but receives an object `{"message_id": x}`,
so it fails with `DecodeFailure "Error in $.result: parsing Integer failed, expected Number, but encountered Object"`

This PR #116 should fix it.

**Comment by swamp-agr** [comment]
Thank you again for reporting and fixing the method. Fix is also released on Hackage: https://hackage.haskell.org/package/telegram-bot-simple-0.5.1

**Comment by swamp-agr** [comment]
Released on Hackage: https://hackage.haskell.org/package/telegram-bot-simple-0.6
