### ISSUE TITLE
`command` UpdateParser is eating newlines

### ISSUE THREAD

**Issue by fetsh** [fizruk/telegram-bot-simple#122]
Currently `command` UpdateParser looks like lthis:
```
command :: Text -> UpdateParser Text
command name = do
  t <- text
  case Text.words t of
    (w:ws) | w == "/" <> name
      -> pure (Text.unwords ws)
    _ -> fail "not that command"
```

And because of `words` -> `unwords` all newlines of the message text vanish.

If this is an intended behavior, then ok.

For myself I'm using my version of `command`:
```
command :: Text -> UpdateParser Text
command name = do
    t <- text
    let (cmd, rest) = Text.break isSpace t
    if cmd == "/" <> name
        then pure $ stripStart rest
        else fail "not that command"
```
I can make a PR with this version, if loosing newlines was not intended and my version is fine codewise.

**Comment by swamp-agr** [comment]
Hi @fetsh-edu, please go ahead and make PR. Please ensure that change will be consistent across other helpers.

**Comment by swamp-agr** [comment]
Released on Hackage: https://hackage.haskell.org/package/telegram-bot-simple-0.6
