### ISSUE TITLE
Upload haddock to hackage

### ISSUE THREAD

**Issue by bsima** [fizruk/telegram-bot-simple#15]
See [here](https://hackage.haskell.org/upload) for how to upload the haddock, plus some troubleshooting steps if it doesn't work automatically.

I believe all you need to do is `stack haddock && stack upload`. 

Note for anyone else looking for the docs: you can build the docs locally, just do `stack haddock` and it will put the docs in somewhere like `/.stack-work/install/x86_64-linux-nix/lts-11.15/8.2.2/doc/telegram-bot-simple-0.2.0/index.html`

**Comment by swamp-agr** [comment]
Docs became available starting from `0.3.0`.
See https://hackage.haskell.org/package/telegram-bot-simple-0.3.0.
