### ISSUE TITLE
New PhoneNumber MessageEntity type

### ISSUE THREAD

**Issue by kosc** [fizruk/telegram-bot-simple#22]
Telegram API now has a new MessageEntity - https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1text_entity_type_phone_number.html

Last time we has the same problem with Cashtag MessageEntity. I think we need some common fix for the problem. It is not good to change type for every change of Telegram API. But for now I just extended the type (wait for my PR please).

**Comment by swamp-agr** [comment]
Closed via #23.
