### ISSUE TITLE
Error using botJob with cron < 0.7

### ISSUE THREAD

**Issue by daapp** [fizruk/telegram-bot-simple#37]
Please, specify cron version as >= 0.7.0 in package.yaml as dependencies, because botJob is unusable otherwise - https://github.com/MichaelXavier/cron/pull/41 . Previous version of cron try to parse incorrect time, for example "2020-11-12 13:60" with error and bot stop working.

**Comment by swamp-agr** [comment]
Hello @daapp, could you please open PR addressing this issue?

**Comment by swamp-agr** [comment]
Closed via #38, #39.
Updated dependency available on hackage: https://hackage.haskell.org/package/telegram-bot-simple-0.3.4
