### ISSUE TITLE
Problems with demo-bot.exe

### ISSUE THREAD

**Issue by OptimusFaber** [fizruk/telegram-bot-simple#43]
So i finally solved all the problems with libraries, but when I'm trying to run exe file to put in Telegram.Token, it's just don't want to work

**Comment by dpwiz** [comment]
* What do you expect to happen?
* What do you do to achieve that?
* What happens instead?

**Comment by swamp-agr** [comment]
Actually there was a problem in cabal file: `DemoBot` was referred to `EchoBot`, so it did not work properly.
Should be fixed in https://hackage.haskell.org/package/telegram-bot-simple-0.4. Please try again. If there're any issues, please re-open it.
