### ISSUE TITLE
Wrong type in EditMessageTextRequest record

### ISSUE THREAD

**Issue by yakuri354** [fizruk/telegram-bot-simple#50]
The `EditMessageTextRequest` type contains a field `editMessageTextRequestInlineMessageId` which has type `MessageId` and is represented as `Int`.
Official Telegram Bot API documentation describes this parameter as a `String`.

#### It would be the right choice to make the `inlineMessageId` field of `EditMessageRequest` represented by `Text` instead of an `Int`

![Screenshot from 2021-09-01 00-24-09](https://user-images.githubusercontent.com/24474728/131578755-42f89e6c-1739-4264-bfb4-7f2ae798860f.png)
![Screenshot from 2021-09-01 00-28-04](https://user-images.githubusercontent.com/24474728/131578763-d9060f63-cb10-40b8-ba81-cad1fbe7b35d.png)

**Comment by swamp-agr** [comment]
Could you please open PR regarding the issue?

**Comment by yakuri354** [comment]
Ok, I'll try to do it as soon as possible

**Comment by swamp-agr** [comment]
Released on Hackage: https://hackage.haskell.org/package/telegram-bot-simple-0.4
