### ISSUE TITLE
Notification in send document can't be disabled

### ISSUE THREAD

**Issue by qnikst** [fizruk/telegram-bot-simple#53]
Even if we set `sendDocumentDisableNotification = Just True`, the message is still sent with notification.

How to reproduce:

1. Send document without notifications:

```haskell
      defaultRunBot (fromString token) $
        sendDocument
          (toSendDocument
             chat_id
              (DocumentFile archive_path "application/zip"))
                { sendDocumentCaption = Just "some caption.zip")
                , sendDocumentDisableNotification = Just True
                }
```

Expected results:

  Message will be delivered without notification. There will be strikethrough bell icon near the message.

Actual results:

  Message is delivered with notifications

**Comment by swamp-agr** [comment]
Released on Hackage: https://hackage.haskell.org/package/telegram-bot-simple-0.3.8
